### ISSUE TITLE
make document-store error: UnicodeEncodeError: 'utf-8' codec can't encode characters in position 16-18: surrogates not allowed

### ISSUE THREAD

**Issue by kuanliang** [the-full-stack/ask-fsdl#70]
When doing make document-store, there are 4 pdf files (our of 299) contain characters can't be encode with utf-8.

with following error messages

`Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/pdfs.py", line 129, in extract_pdf
    documents = etl.shared.enrich_metadata(documents)
  File "/root/etl/shared.py", line 45, in enrich_metadata
    m.update(page["text"].encode("utf-8", 'surrogateescape'))
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 16-18: surrogates not allowed`

**Comment by charlesfrye** [comment]
```python
File "/root/etl/shared.py", line 45, in enrich_metadata 
m.update(page["text"].encode("utf-8", 'surrogateescape')
```

The code in this error message doesn't match [the code on main](https://github.com/the-full-stack/ask-fsdl/blob/b2ae7bbf98d401013f49eebcd8d5b44567bbb455/etl/shared.py#L44-L46). Did you make local edits?

Yes, some of the PDFs contain invalid characters -- the behavior of the code right now is to throw a warning. The PDFs end up in the document store but they are generally ignored during retrieval.

**Comment by charlesfrye** [comment]
This was actually a new failure -- new behavior on the part of one of the PDF parsers, most likely.

I tightened up the dependency down to the minor version there and also added some code to handle bad Unicode 1017b12
